name: Ejecutar Pruebas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Dar permisos y agregar vitest al PATH
        shell: bash
        run: |
          chmod +x ./node_modules/.bin/vitest || true
          echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Ejecutar pruebas
        run: npm run test
